# Generated by Django 5.1.6 on 2025-02-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='action_taken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='action_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
