# Generated by Django 5.1.6 on 2025-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_reviewed_by_alter_servicerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
